### ISSUE TITLE
Lazy-load files

### ISSUE THREAD

**Issue by srph** [vkeusebio/ug#3]
Right now, all files are being loaded on start. It would be more performant if we would only load files that are included in the form request.

Unfortunately, I'm at work at the moment. But I can send a PR tonight or tomorrow.

**Comment by vkeusebio** [comment]
Thank you for taking the time to check this project out, sure, submit a PR. Can you describe how would you do it? And which particular files should be loaded on request?

**Comment by srph** [comment]
```php
if ( $request->has('yolo') )
  file_get_contents('yolo')
```

**Comment by srph** [comment]
Also, we should use Symfony's `File` class instead of dealing with it with low-level functions.

**Comment by vkeusebio** [comment]
I see, to be honest I'm still new to Laravel/Lumen so I don't really know how to leverage the use of the framework. Thank you again :smiley:

**Comment by srph** [comment]
No problem, man &mdash; we're here to discuss anyway. (my monotonous way of speaking has made me sound negative, sorry about that).

Be back on this tonight.

**Comment by srph** [comment]
https://github.com/vkeusebio/ug/pull/4
