### ISSUE TITLE
Queue deletion of generated css files

### ISSUE THREAD

**Issue by srph** [vkeusebio/ug#5]
Not sure if deleting it on the go can become a bottle neck.

Does the host (host of ug) allow CRON?

**Comment by vkeusebio** [comment]
Heroku doesn't support CRON jobs but they have [Heroku Scheduler](https://devcenter.heroku.com/articles/scheduler) which is similar to CRON.

**Comment by vkeusebio** [comment]
I just received a notification regarding my credit card balance, it was because of heroku's Dyno-hour cost. I guess I have to manually clean the `download/` directory.

**Comment by srph** [comment]
Or we could just delete it.

**Comment by srph** [comment]
Sadly.
