### ISSUE TITLE
500 Error

### ISSUE THREAD

**Issue by srph** [vkeusebio/ug#7]
Right now, the app is down. I have no access, so I'm not sure how I can help.

![screen shot 2016-01-08 at 6 27 25 am](https://cloud.githubusercontent.com/assets/5093058/12184548/d43ab9d8-b5d0-11e5-9604-379b0f98d21c.png)

**Comment by vkeusebio** [comment]
It must be the `.env`, will fix in a minute.

**Comment by vkeusebio** [comment]
fixed it :ok_hand:

**Comment by vkeusebio** [comment]
oops.
```php
Fatal error: Call to undefined function App\Jobs\public_path()
```
wait a minute.

**Comment by srph** [comment]
Run `composer dumpautoload` on the Heroku instance.

**Comment by vkeusebio** [comment]
I already did that but it still can't find the helpers class.

**Comment by srph** [comment]
Weird, it's not a class though, it's just a file located at `app/`
